
skillMetadata:
  sections:
    - name: Your Moodle URL
      fields:
        - name: domainname
          type: text
          label: ex. https://foo.bar/moodle
          value: ""
          placeholder: demo prompt in the input box
    - name: Your Moodle Course ID
      fields:
        - name: courseid
          type: text
          label: ex. 1
          value: ""
          placeholder: demo prompt in the input box
    - name: Moodle account
      fields:
        - type: label
          label: Your Moodle account
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
